#!/bin/bash
# updates packages; tries dnf first, then apt-get

function command_exists {
	# http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
	type $1 &> /dev/null
}

if command_exists dnf ;
then
	sudo dnf upgrade -y
	exit $?
fi


if command_exists apt-get ;
then
	sudo apt-get update && sudo apt-get dist-upgrade -y && sudo apt-get autoremove -y
	exit $?
fi

echo "Couldn't find dnf or apt-get, exiting." 1>&2;
exit 1
